cleancheck: smaller improvements and autoinstallation

diff --git a/Scripts/cleancheck b/Scripts/cleancheck
--- a/Scripts/cleancheck
+++ b/Scripts/cleancheck
@@ -11,7 +11,7 @@
 option_h()
 {
 echo "$0 [-a PATH] [-c PATH] [-l NAME] [-e DIRS] [-h] [-s PATH] [-w ACPSU]"
-echo "-a set path to clamscan  binary. if not set /usr/bin/clamscan is used"
+echo "-a set path to clamscan  binary. if not set, which clamscan is used"
 echo "-c set path to  chkrootkit binary. if not set /usr/bin/rkhunter is used"
 echo "-e exclude these dirs for scanning for viruses"
 echo "   you have to seperate the directories by : character"
@@ -131,17 +131,17 @@ shift `expr $OPTIND - 1`
 
 if [ -z $ANTIVIR ]
 	then
-		ANTIVIR="/usr/bin/clamscan" #enter the path to clamscan or the path to your virus scanner
+		ANTIVIR=$(which clamscan || echo "no") #enter the path to clamscan or the path to your virus scanner
 fi
 
 if [ -z $ROOTKIT_CHECKER ]
 	then
-		ROOTKIT_CHECKER="/usr/bin/rkhunter" #enter the path to your rootkitchecker
+		ROOTKIT_CHECKER=$(which rkhunter || echo "no") #enter the path to your rootkitchecker
 fi
 
 if [ -z $SECURITY_CHECKER ] #check for open security holes
 	then
-		SECURITY_CHECKER="/usr/bin/lynis"
+		SECURITY_CHECKER=$(which lynis || echo "no")
 fi
 
 if [ -z $USE_QUIET ]
@@ -196,13 +196,14 @@ fi
 
 #check whether programs and argumets are set correctly
 check_antivir()
-{
-TEST_AV=$(${ANTIVIR} -V|grep ClamAV  2> /dev/null || echo "no" )	
+{	
 echo "checking for $ANTIVIR" 2> /dev/null
-if [ "$TEST_AV" = "no" ]
+if [ "$ANTIVIR" = "no" ]
 	then
 		drop_failure
-		echo "$ANTIVIR is not a valid clamav installation"
+		echo "$ANTIVIR is not installed."
+		echo "trying to get one"
+		aptitude install -y clamav clamav-freshclam || zypper in clamav clamav-db || we_fail
 		exit 1
 	else
 		drop_ok
@@ -213,13 +214,13 @@ fi
 
 check_rootkit_checker()
 {
-TEST_CH=$(${ROOTKIT_CHECKER} --version | grep rkhunter || echo "no")
 echo "checking for $ROOTKIT_CHECKER" 2> /dev/null
-if [ "$TEST_CH" = "no" ] 
+if [ "$ROOTKIT_CHECKER" = "no" ] 
 	then
 		drop_failure
-		echo "$ROOTKIT_CHECKER is not a valid rootkitcheker"
-		exit 1
+		echo "$ROOTKIT_CHECKER is not installed"
+		echo "trying to get one"
+		aptitude install -y rkhunter || zypper in rkhunter || we_fail
 	else
 		drop_ok
 fi
@@ -227,13 +228,13 @@ fi
 
 check_lynis()
 {
-TEST_LY=$(${SECURITY_CHECKER} -V | grep [0-9] 2> /dev/null || echo "no")
 echo "checking for $SECURITY_CHECKER" 2> /dev/null
-if [ "$TEST_LY" = "no" ]
+if [ "$SECURITY_CHECKER" = "no" ]
 	then
 		drop_failure
-		echo "$SECURITY_CHECKER is not a valid security checker"
-		exit 1
+		echo "$SECURITY_CHECKER is not a installed"
+		echo "trying to get one"
+		aptitude install -y lynis || zypper in lynis || we_fail
 	else
 		drop_ok
 fi
@@ -573,6 +574,13 @@ drop_ok ()
 echo -e '\t \t \t \t \E[32mok'; tput sgr0
 }
 
+we_fail()
+{
+echo "failed"	
+echo "stop"
+exit 1
+}
+
 check_root
 
 exit 0
@@ -594,3 +602,5 @@ exit 0
 #if rkhunter database is not created creta this first. use rkhunter --proupd in an f statement to do this
 #test whether packages match if not install them
 #use aide to prevent filesystem infiltration
+#check for both rkhunter and chkrootkit
+#implement all stuff in a nicer interface
